### ISSUE TITLE
Application shows as installed even when it's not

### ISSUE THREAD

**Issue by direc85** [mentaljam/harbour-storeman#100]
I was supposed to have Tint Overlay installed, but I suspect it was removed during OS upgrade to 3.1.0 EA. I can't find the icon, but Storeman tells me it is installed but only shows its package name `harbour-tint-overlay`. Using `pkcon search harbour-tint-overlay` shows it's available, but not installed. I can try to launch or remove it using Storeman, but they obviously fail. If I install it from command line and restart Storeman, the application now shows the correct name, Tint Overlay, and can be manipulated again as expected.

It seems that refreshing the installed packages list does not properly get the status of the packages, or am I misinterpreting the function?

I made a backup using Storeman and deleted `.config/harbour-storeman`, `.local/share/harbour-storeman` and `.cache/harbour-storeman` directories. I then started Storeman, and `harbour-tint-overlay` is back! How is that possible?

**Comment by mentaljam** [comment]
There are some issues with 3.1.0 (#99). I think they are all have the same reason and I'll try to fix them soon.

**Comment by direc85** [comment]
I issued `zypper refresh` and it seems to have fixed this specific issue; Tint Overlay doesn't show as "installed" after purging Storeman data folders.

**Comment by direc85** [comment]
Nope, it didn't... It's back with Patchmanager...

**Comment by mentaljam** [comment]
Storeman gets installed packages with libsolv so purging its data cannot fix such issues. Please consider close this one if the last release works fine.

**Comment by direc85** [comment]
I don't think I've seen this behavior for quite a good while, closing this bug (I forgot about, sorry about that).
