### ISSUE TITLE
can't install on SOS v3.1.0.11

### ISSUE THREAD

**Issue by atgc220** [mentaljam/harbour-storeman#104]
After adding the repo, only "Refresh cache" and "Reload" are shown, but not "Install".
Thanks for your assistance.
Patrick

**Comment by mentaljam** [comment]
I use Storeman on 3.1.0.11 with no problems. Did you try `devel-su pkcon refresh`?

**Comment by atgc220** [comment]
Thanks for your reply.

Yes, however install still doesn't show

**Comment by mentaljam** [comment]
No applications can be installed or a particular one?

**Comment by atgc220** [comment]
None .
i own another xa2 with the same release, and did not encounter this problem .

**Comment by bolinches** [comment]
I am having the same with XA2 3.2.1.20

**Comment by bolinches** [comment]
Nevermind 0.1.7-1 update and works now
