### ISSUE TITLE
Search field overlaps string about searching results

### ISSUE THREAD

**Issue by atlochowski** [mentaljam/harbour-storeman#117]
How to reproduce:

 Open Storeman -> Installed aplications -> tap and hold on app -> Search in OprenRepos.net  - > Delete app name from search field by pressing "x" button

**Comment by GNUuser** [comment]
Hi @atlochowski  you mean this??
![Captura_20200504_003](https://user-images.githubusercontent.com/45316884/82171238-b9eb2a80-9894-11ea-985b-8500ff9e99bd.png)

**Comment by atlochowski** [comment]
exactly this

**Comment by mentaljam** [comment]
Sorry for ignoring the issue. I fixed it about a month ago but did not publish a release.

**Comment by atlochowski** [comment]
thanks for fixing!
