### ISSUE TITLE
[question]  restore storeman's repo list and installed software list from .tar backup of root

### ISSUE THREAD

**Issue by erikderzweite** [mentaljam/harbour-storeman#123]
I have bricked my Sailfish device (something with LUKS), but I have tar files of root and home partitions.

Now I'm trying to restore the device without having to configure everything again.

I have overwritten /usr and /var from backups, most things seem to work. But I can't restore storeman's lists of repositories and installed software. Is there a way to restore these data from my .tar backup?

Which files/databases does storeman use to store repo list and software list.

**Comment by mentaljam** [comment]
Storeman uses [SSU](https://git.sailfishos.org/mer-core/ssu/) to manage repositories. Which under the hood uses [libzypp](https://github.com/openSUSE/libzypp). SSU stores all repository URLs in `/etc/ssu/ssu.ini` under the `[repository-urls]` section. OpenRepos repositories are prefixed with `openrepos-`.

I don't know which files exactly you need to copy, you need to study libzypp to find all the required files (configuration, cache, keys, etc.). May be it is easier to re-add your repositories (listed in backed-up `ssu.ini`) with SSU or zypper cli.

**Comment by mentaljam** [comment]
Have you managed to solve your issue?

**Comment by erikderzweite** [comment]
Yes, thank you. Copyings /etc/ssu/ has restored the installed apps' and repositories' settings correctly.
