### ISSUE TITLE
Network is unavailable!

### ISSUE THREAD

**Issue by wickedsp1d3r** [mentaljam/harbour-storeman#126]
Storeman detects that I have no network, but I have no issues with my connection.

```
$ harbour-storeman
[D] unknown:0 - Using Wayland-EGL
[W] unknown:0 - Network is unavailable!
```

**Comment by mentaljam** [comment]
Storeman doesn't work or it's only a message?

**Comment by wickedsp1d3r** [comment]
Storeman in unusable. It opens but basically nothing works.
Does the application depend on ConnMan's online status?
I have this:

```
$ connmanctl state
    State = ready
    OfflineMode = False
    SessionMode = False
    InputRequestTimeout = 300000
```
If so, can I "cheat" Storeman to detect I have a working connection?

**Comment by mentaljam** [comment]
> Does the application depend on ConnMan's online status?

Yes, [it does](https://github.com/mentaljam/harbour-storeman/blob/7f29e70405362fa7a66e9ed56bef9fa9965a4c16/qml/harbour-storeman.qml#L101). Did you changed you ConnMan's config somehow? As a quick solution you can patch harbour-storeman.qml on your device:

```qml
readonly property bool online: !state || state === "online" || state === "ready"
```

**Comment by wickedsp1d3r** [comment]
Thank you for the tip.
I use a custom DNS resolver outside ConnMan so it is not able to check online status.

My `/usr/share/harbour-storeman/qml/harbour-storeman.qml` has now the following modification:
```
...
NetworkManager {   
        readonly property bool online: !state || state === "online" || state === "ready"
        
        id: networkManager
    }
...
```
However, it seems like this is not enough. I still get the error message when I launch the application:
```
$ harbour-storeman
[D] unknown:0 - Using Wayland-EGL
[W] unknown:0 - Network is unavailable!
[W] unknown:0 - libpng warning: iCCP: known incorrect sRGB profile
```
I am now able to search applications with Storeman, but I can't add any repositories - the same error message is printed to stdout when I try to do so.

**Comment by mentaljam** [comment]
I realised that I also compare the state to "online" in the C++ part of code. I will check if I can add "ready" to supported states with no regressions.

**Comment by wickedsp1d3r** [comment]
Great. Let me know if you can add it.

**Comment by mentaljam** [comment]
@wickedsp1d3r, could you check out this [version](https://github.com/mentaljam/harbour-storeman/files/5264041/harbour-storeman-0.2.0-1.armv7hl.zip)?

**Comment by wickedsp1d3r** [comment]
> @wickedsp1d3r, could you check out this [version](https://github.com/mentaljam/harbour-storeman/files/5264041/harbour-storeman-0.2.0-1.armv7hl.zip)?

It seems like everything is working smoothly with this version. Many thanks! I will report back if I face any issues with it.
