### ISSUE TITLE
FeatureRequest: change string of word for a share-sailfish-icon.

### ISSUE THREAD

**Issue by GNUuser** [mentaljam/harbour-storeman#129]
![Captura_20200820_001_edit](https://user-images.githubusercontent.com/45316884/90977880-35edb200-e517-11ea-8e01-88c63321ac33.png)
![Captura_20200819_001_edit](https://user-images.githubusercontent.com/45316884/90977885-3d14c000-e517-11ea-81ab-22ac4934e199.png)

**Comment by mentaljam** [comment]
Hi,

Why did you closed it? Just leave open and close with the appropriate commit :)

**Comment by GNUuser** [comment]
> Hi,
> 
> Why did you close it? Just leave open and close with the appropriate commit :)

Thank you. I was think that a share-icon looks better also translationless.

**Comment by mentaljam** [comment]
Yes, it's a good idea. I wonder why I didn't come to it myself.

**Comment by mentaljam** [comment]
> WIP

Sorry, I didn't quite understand. Should I wait a PR from you?

**Comment by GNUuser** [comment]
> > WIP
> 
> Sorry, I didn't quite understand. Should I wait a PR from you?

Not from me. I waiting the PR from you, you have better sailfish skills. sorry for WIP message i delete  now.
