### ISSUE TITLE
Installation error on Sailfish OS versions 3.4.0.22 & 3.4.0.24

### ISSUE THREAD

**Issue by rigo** [mentaljam/harbour-storeman#135]
Trying to install Storeman on Sailfish OS versions 3.4.0.22 & 3.4.0.24 gives an error saying there is nothing that provides libsolv.so.0 which is needed.

**Comment by mentaljam** [comment]
Hi! Try to install this [package](https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.2-1/harbour-storeman-0.2.2-1.armv7hl.rpm).

**Comment by mschilli87** [comment]
I am on Sailfish OS 3.3.0.16 (Rokua) and

```sh
sudo zypper install harbour-storeman
```

gives me

```
Password:
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libsolv.so.1 needed by harbour-storeman-0.2.7-1~sfos4.1.armv7hl
 Solution 1: do not install harbour-storeman-0.2.7-1~sfos4.1.armv7hl
 Solution 2: break harbour-storeman-0.2.7-1~sfos4.1.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): c
```

I tried 

```sh
sudo zypper install https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.2-1/harbour-storeman-0.2.2-1.armv7hl.rpm
```

but got the same (but for the different version):

```
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libsolv.so.1 needed by harbour-storeman-0.2.2-1.armv7hl
 Solution 1: do not install harbour-storeman-0.2.2-1.armv7hl
 Solution 2: break harbour-storeman-0.2.2-1.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): c
```

**Comment by mentaljam** [comment]
@mschilli87, there is a special package for sfos3.3 https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.7-1/harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm

**Comment by mschilli87** [comment]
@mentaljam: Thx for the quick response.

```sh
sudo zypper install \
  https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.7-1/harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm
```

gives me

```
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides sailfish-version = 3.3 needed by harbour-storeman-0.2.7-1~sfos3.3.armv7hl
 Solution 1: do not install harbour-storeman-0.2.7-1~sfos3.3.armv7hl
 Solution 2: break harbour-storeman-0.2.7-1~sfos3.3.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): c
```

Is it safe to ignore this 'dependency'?

Also, is there a way to get this via a repository instead of manually downloading RPMs after asking around which one to get?

I did try

```sh
ssu addrepo osetr http://sailfish.openrepos.net/osetr/personal/main
```

assuming `zypper` would figure out the correct file to use.
But maybe I am just spoiled by the package managers I am used to using. :wink:

Thank you for you work on this and the great support on top of it.

**Comment by mschilli87** [comment]
I did try installing the package manually regardless:

```sh
sudo zypper install \
  https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.7-1/harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm
```

```
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides sailfish-version = 3.3 needed by harbour-storeman-0.2.7-1~sfos3.3.armv7hl
 Solution 1: do not install harbour-storeman-0.2.7-1~sfos3.3.armv7hl
 Solution 2: break harbour-storeman-0.2.7-1~sfos3.3.armv7hl by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): 2
Resolving dependencies...
Resolving package dependencies...

The following 10 NEW packages are going to be installed:
  harbour-storeman libsailfishcrypto libsailfishcryptopluginapi libsailfishsecrets
  libsailfishsecretspluginapi qt5-plugin-sqldriver-sqlcipher sailfishsecretsdaemon
  sailfishsecretsdaemon-secretsplugin-common sailfishsecretsdaemon-secretsplugins-default
  sqlcipher

10 new packages to install.
Overall download size: 1.6 MiB. Already cached: 0 B. After the operation, additional 5.0 MiB
will be used.
Continue? [y/n/...? shows all options] (y):
Retrieving package libsailfishcrypto-0.2.17-1.12.1.jolla.armv7hl
                                                           (1/10), 211.1 KiB (746.2 KiB unpacked)
Retrieving: libsailfishcrypto-0.2.17-1.12.1.jolla.armv7hl.rpm .............................[done]
Retrieving package libsailfishsecrets-0.2.17-1.12.1.jolla.armv7hl
                                                           (2/10), 155.5 KiB (412.7 KiB unpacked)
Retrieving: libsailfishsecrets-0.2.17-1.12.1.jolla.armv7hl.rpm ............................[done]
Retrieving package sqlcipher-3.4.1+git2-1.3.1.jolla.armv7hl
                                                           (3/10), 261.2 KiB (633.9 KiB unpacked)
Retrieving: sqlcipher-3.4.1+git2-1.3.1.jolla.armv7hl.rpm ..................................[done]
Retrieving package libsailfishsecretspluginapi-0.2.17-1.12.1.jolla.armv7hl
                                                           (4/10),  34.8 KiB ( 17.7 KiB unpacked)
Retrieving: libsailfishsecretspluginapi-0.2.17-1.12.1.jolla.armv7hl.rpm ...................[done]
Retrieving package qt5-plugin-sqldriver-sqlcipher-0.2.17-1.12.1.jolla.armv7hl
                                                           (5/10),  46.9 KiB ( 50.3 KiB unpacked)
Retrieving: qt5-plugin-sqldriver-sqlcipher-0.2.17-1.12.1.jolla.armv7hl.rpm ................[done]
Retrieving package libsailfishcryptopluginapi-0.2.17-1.12.1.jolla.armv7hl
                                                           (6/10),  31.8 KiB (  9.5 KiB unpacked)
Retrieving: libsailfishcryptopluginapi-0.2.17-1.12.1.jolla.armv7hl.rpm ....................[done]
Retrieving package sailfishsecretsdaemon-0.2.17-1.12.1.jolla.armv7hl
                                                           (7/10), 355.3 KiB (935.8 KiB unpacked)
Retrieving: sailfishsecretsdaemon-0.2.17-1.12.1.jolla.armv7hl.rpm ............[done (15.4 KiB/s)]
Retrieving package sailfishsecretsdaemon-secretsplugin-common-0.2.17-1.12.1.jolla.armv7hl
                                                           (8/10), 127.7 KiB (304.3 KiB unpacked)
Retrieving: sailfishsecretsdaemon-secretsplugin-common-0.2.17-1.12.1.jolla.armv7hl.rpm ....[done]
Retrieving package sailfishsecretsdaemon-secretsplugins-default-0.2.17-1.12.1.jolla.armv7hl
                                                           (9/10),  73.2 KiB (136.3 KiB unpacked)
Retrieving: sailfishsecretsdaemon-secretsplugins-default-0.2.17-1.12.1.jolla.armv7hl.rpm ..[done]
Retrieving package harbour-storeman-0.2.2-1.armv7hl       (10/10), 372.1 KiB (  1.8 MiB unpacked)
harbour-storeman-0.2.2-1.armv7hl.rpm:
    Package is not signed!

harbour-storeman-0.2.2-1.armv7hl (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Abort, retry, ignore? [a/r/i] (a): i
Checking for file conflicts: ..............................................................[done]
( 1/10) Installing: libsailfishcrypto-0.2.17-1.12.1.jolla.armv7hl .........................[done]
Additional rpm output:
warning: /var/cache/zypp/packages/jolla/oss/armv7hl/libsailfishcrypto-0.2.17-1.12.1.jolla.armv7hl.rpm: Header V3 DSA/SHA1 Signature, key ID f2633ee0: NOKEY


( 2/10) Installing: libsailfishsecrets-0.2.17-1.12.1.jolla.armv7hl ........................[done]
Additional rpm output:
warning: /var/cache/zypp/packages/jolla/oss/armv7hl/libsailfishsecrets-0.2.17-1.12.1.jolla.armv7hl.rpm: Header V3 DSA/SHA1 Signature, key ID f2633ee0: NOKEY


( 3/10) Installing: sqlcipher-3.4.1+git2-1.3.1.jolla.armv7hl ..............................[done]
Additional rpm output:
warning: /var/cache/zypp/packages/jolla/core/armv7hl/sqlcipher-3.4.1+git2-1.3.1.jolla.armv7hl.rpm: Header V3 DSA/SHA1 Signature, key ID f2633ee0: NOKEY


( 4/10) Installing: libsailfishsecretspluginapi-0.2.17-1.12.1.jolla.armv7hl ...............[done]
Additional rpm output:
warning: /var/cache/zypp/packages/jolla/oss/armv7hl/libsailfishsecretspluginapi-0.2.17-1.12.1.jolla.armv7hl.rpm: Header V3 DSA/SHA1 Signature, key ID f2633ee0: NOKEY


( 5/10) Installing: qt5-plugin-sqldriver-sqlcipher-0.2.17-1.12.1.jolla.armv7hl ............[done]
Additional rpm output:
warning: /var/cache/zypp/packages/jolla/oss/armv7hl/qt5-plugin-sqldriver-sqlcipher-0.2.17-1.12.1.jolla.armv7hl.rpm: Header V3 DSA/SHA1 Signature, key ID f2633ee0: NOKEY


( 6/10) Installing: libsailfishcryptopluginapi-0.2.17-1.12.1.jolla.armv7hl ................[done]
Additional rpm output:
warning: /var/cache/zypp/packages/jolla/oss/armv7hl/libsailfishcryptopluginapi-0.2.17-1.12.1.jolla.armv7hl.rpm: Header V3 DSA/SHA1 Signature, key ID f2633ee0: NOKEY


( 7/10) Installing: sailfishsecretsdaemon-0.2.17-1.12.1.jolla.armv7hl .....................[done]
Additional rpm output:
warning: /var/cache/zypp/packages/jolla/oss/armv7hl/sailfishsecretsdaemon-0.2.17-1.12.1.jolla.armv7hl.rpm: Header V3 DSA/SHA1 Signature, key ID f2633ee0: NOKEY


( 8/10) Installing: sailfishsecretsdaemon-secretsplugin-common-0.2.17-1.12.1.jolla.armv7hl [done]
Additional rpm output:
warning: /var/cache/zypp/packages/jolla/oss/armv7hl/sailfishsecretsdaemon-secretsplugin-common-0.2.17-1.12.1.jolla.armv7hl.rpm: Header V3 DSA/SHA1 Signature, key ID f2633ee0: NOKEY


( 9/10) Installing: sailfishsecretsdaemon-secretsplugins-default-0.2.17-1.12.1.jolla.armv7h[done]
Additional rpm output:
warning: /var/cache/zypp/packages/jolla/oss/armv7hl/sailfishsecretsdaemon-secretsplugins-default-0.2.17-1.12.1.jolla.armv7hl.rpm: Header V3 DSA/SHA1 Signature, key ID f2633ee0: NOKEY


(10/10) Installing: harbour-storeman-0.2.2-1.armv7hl ......................................[done]
```

This gave me a Storeman icon in my app list but tapping does not open the app.

I tried getting some more information by launching it from the terminal:

```sh
harbour-storeman
```

```
harbour-storeman: error while loading shared libraries: libsolv.so.1: cannot open shared object file: No such file or directory
```

So I guess there still is any issue with `libsolv` after all...

**Comment by mentaljam** [comment]
> `Problem: nothing provides sailfish-version = 3.3`

Do you use a community port? I don't know much about ports, maybe `sailfish-version` is unavailable for them? For now I use this package to explicitly restrict the installation of certain builds of storeman on certain SFOS versions.

> I did try installing the package manually regardless...
> `Retrieving package harbour-storeman-0.2.2-1.armv7hl       (10/10), 372.1 KiB (  1.8 MiB unpacked)`

Zypper installed a wrong version for SFOS 4 which has libsolv.so.1 while SFOS 3 has libsolv.so.0. I may suggest you to try to install an appropriate `sailfish-version` package or to install [harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm](https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.7-1/harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm) manually with `pkcon install-local harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm`.

**Comment by mschilli87** [comment]
> > `Problem: nothing provides sailfish-version = 3.3`
> 
> Do you use a community port?

Yes indeed. Sorry for not bringing this up earlier.

> I don't know much about ports, maybe `sailfish-version` is unavailable for them? For now I use this package to explicitly restrict the installation of certain builds of storeman on certain SFOS versions.

It seems `zypper` disagrees:

```sh
zypper se sailfish-version
```

```
Loading repository data...
Reading installed packages...

S | Name                     | Summary                             | Type
--+--------------------------+-------------------------------------+--------
i | sailfish-version         | Sailfish OS 3.3.0.16 (release)      | package
  | sailfish-version-doc     | Sailfish OS 3.3.0.16 (release)      | package
i | sailfish-version-variant | Sailfish OS release variant package | package
```
 
> > I did try installing the package manually regardless...
> > `Retrieving package harbour-storeman-0.2.2-1.armv7hl       (10/10), 372.1 KiB (  1.8 MiB unpacked)`
> 
> Zypper installed a wrong version for SFOS 4 which has libsolv.so.1 while SFOS 3 has libsolv.so.0.

Sorry if I am doing something fundamentally wrong. I haven't used RPM-based distros in well over a decade and even back then never really used any of them as a primary system.

> I may suggest you to try to install an appropriate `sailfish-version` package or to install [harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm](https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.7-1/harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm) manually with `pkcon install-local harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm`.

Since apparantly I do have `sailfish-version` (and I'd assume `3.3.0.16` to satisfy a `3.3` dependence), I opted for the 2nd approach:

```sh
curl -L \
  -o /tmp/harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm \
  https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.7-1/harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm
sudo pkcon install-local /tmp/harbour-storeman-0.2.7-1.sfos3.3.armv7hl.rpm
```

Unfortunately, that brings us back to sqaure one (or rather two? :wink:):

```
Installing files
Testing changes
Finished
Fatal error: nothing provides sailfish-version = 3.3 needed by harbour-storeman-0.2.7-1~sfos3.3.armv7hl
```

Just in case this helps to further narrow down the issue:

```sh
sudo zypper in sailfish-version
```

```
Loading repository data...
Reading installed packages...
'sailfish-version' is already installed.
No update candidate for 'sailfish-version-3.3.0-1.16.16.jolla.noarch'. The highest available version is already installed.
Resolving package dependencies...

Nothing to do.
```

Thanks again for your ongoing support and sorry for needing to be taken by the hand like this.

**Comment by mentaljam** [comment]
> Thanks again for your ongoing support and sorry for needing to be taken by the hand like this.

Don't worry! I have provided a special package for SFOS 3.3 that doesn't work. It is logical to work on fixing it :)

I'll take a closer look at the dependencies being generated for my RPMs, maybe I would find something.

**Comment by mschilli87** [comment]
@mentaljam: If there's anything I could do in the meantime to help you help me, please let me know.

**Comment by dennisroczek** [comment]
I have the same problem with the volla phone which has only a community port to 3.4 :-(

**Comment by mentaljam** [comment]
Sorry for a long reply. @mschilli87, @dennisroczek can you, please, try to install this RPM [harbour-storeman-0.2.7-1~sfos3.3.armv7hl.zip](https://github.com/mentaljam/harbour-storeman/files/6729305/harbour-storeman-0.2.7-1.sfos3.3.armv7hl.zip)?

**Comment by mschilli87** [comment]
@mentaljam:

Perfect! That one installed just fine (via  `pkcon`) and I successfully added a repo and installed an app from it using Storeman. :tada: 

Thank you for your (IMHO fast!) fix and the great service you provide to the community by maintaining this software for free. :heart:

**Comment by dennisroczek** [comment]
Doesn't work.

I get the error that libsolv.so.0 is missing.

using whereis 
libsolv.so.1 is found in /usr/lib

trying to install harbor 2.7.1 for sfos4 is not possible as it says that sailfish version >=4.1 is needed. :-(

Deadlocked.

**Comment by mschilli87** [comment]
@dennisroczek: Note that I am on 3.3 and you seem to be o 3.4. The link @mentaljam provided explicitly mentions 3.3, so maybe that is why it works for me but not for you?

**Comment by dennisroczek** [comment]
> @dennisroczek: Note that I am on 3.3 and you seem to be o 3.4. The link @mentaljam provided explicitly mentions 3.3, so maybe that is why it works for me but not for you?

very likely. And the ticket is about sfos 3.4 😛

**Comment by dennisroczek** [comment]
> Hi! Try to install this [package](https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.2-1/harbour-storeman-0.2.2-1.armv7hl.rpm).

ouch. Didn't see that package! 🤦 That package does work for me! Thanks.

**Comment by dennisroczek** [comment]
> > > Hi! Try to install this [package](https://github.com/mentaljam/harbour-storeman/releases/download/v0.2.2-1/harbour-storeman-0.2.2-1.armv7hl.rpm).
> > 
> > 
> > ouch. Didn't see that package! 🤦 That package does work for me! Thanks.
> 
> But this is an old version. The current one is 0.2.7. 
Yeah, but having any storeman is better than having no storeman. ;-)

> Seems that I've got completely confused with SFOS versions. The libsolv was updated in 3.4, but I thought that it was in SFOS 4.0.
> 
> So I need to downgrade the minimum required SFOS version for `harbour-storeman-0.2.7-1.sfos4.1.rpm` to SFOS 3.4.
👍

**Comment by mentaljam** [comment]
@mschilli87, @dennisroczek please try to install these packages:

- For SFOS 3.3 - [harbour-storeman-0.2.7-1~sdk3.3.0.14.armv7hl.zip](https://github.com/mentaljam/harbour-storeman/files/6812199/harbour-storeman-0.2.7-1.sdk3.3.0.14.armv7hl.zip)
- For SFOS 3.4 - [harbour-storeman-0.2.7-1~sdk4.1.0.24.armv7hl.zip](https://github.com/mentaljam/harbour-storeman/files/6812207/harbour-storeman-0.2.7-1.sdk4.1.0.24.armv7hl.zip)

**Comment by mschilli87** [comment]
@mentaljam:

I am getting a 

```
The selected package 'harbour-storeman-0.2.7-1~sdk3.3.0.14.armv7hl' from repository 'Plain RPM files cache' has lower version than the installed one. Use 'zypper install --oldpackage harbour-storeman-0.2.7-1~sdk3.3.0.14.armv7hl' to force installation of the package.
There is an update candidate 'harbour-storeman-0.2.7-1~sfos4.1.armv7hl' for 'harbour-storeman-0.2.7-1~sfos3.3.armv7hl', but it does not match the specified version, architecture, or repository.
```
warning.
Should I still install/downgrade from the working version I have?

**Comment by mentaljam** [comment]
@mschilli87, it happens because `sdk3.3.0.14` is lexicographically less than `sfos3.3`. I decided to change the naming schema because now it doesn't show the target OS version but the SDK which was used for building the package.

Anyway, just ignore the warning. We need to check if this rpm will be installed on your device.

**Comment by mschilli87** [comment]
@mentaljam: Seem to be working fine AFAICT.

**Comment by mentaljam** [comment]
I consider this problem to be solved and am closing it. If not, please reopen
