### ISSUE TITLE
It takes several minutes for Storeman to open sometimes

### ISSUE THREAD

**Issue by hetas** [mentaljam/harbour-storeman#137]
Sometimes it takes Storeman several minutes to open. When this happens it's repeateable, so if you close the app and then reopen it again takes a long time.

When you try to open the app the cover is shown with the spinning loader for a little while and then the cover disappears as if the app had crashed but then after a few minutes the Storeman window opens.

I also tried to open Storeman from the terminal with the command "harbour-storeman" and no such problem occured. Storeman was opened just fine.

I'm pretty sure that this happens when I've already used the app and given the confirmation to use Sailfish secrets. But I'm not 100% sure so this could have something to do with that. The confirmation dialog is not shown at least with this instance where the log is from.

EDIT: This just happened again and I did not get the Sailfish Secrets confirmation dialog at all. So my guess is that the dialog is not shown to the user and after some timeout the app window is opened.

Journalctl log attached. Log begins from around the time where I tap to open Storeman and ends when the app windows is actually shown. I hope, I did trim the log from the beginning.

[jolla.log](https://github.com/mentaljam/harbour-storeman/files/5579242/jolla.log)

Sony Xperia XA2
SaifishOS 3.4.0.24 in Finnish
Storeman 0.2.2

**Comment by mentaljam** [comment]
Hi,
Thank you for the logs! Unfortunately, there is not much information here, because you use a release version. Here is a debug version with more verbose output. Can you, please, use it to provide more information?

[harbour-storeman-0.2.3-master.armv7hl.zip](https://github.com/mentaljam/harbour-storeman/files/5612043/harbour-storeman-0.2.3-master.armv7hl.zip)

**Comment by hetas** [comment]
I installed the debug version and tried it. I actually got a different kind of secrets dialog but only when I had the settings app opened. This dialog was shown in the settings window, not as a separate dialog.

If I didn't have the settings app opened then I got the same result as before. No secrets dialog and it took a long time for Storeman to open.

I tried to repeat this and just got the normal dialog this time without a delay. So the problem does not repeat every time.

The dialog is in Finnish but loosely translated it says

"Give permission. Sailfish OS would like to get a secret from  cookie plugins SQLChiper collection called storeman."

If I tap OK, the last line in the picture appears and says "Incorrect access code". The dialog remains.

When I tap he X, dialog is closed and Storeman opens.

There's two logs attached. One with this new kind of dialog, and one where no dialog was shown and it took a long time for Storeman to open. Hope they help. For me it didn't look like there's much more information.

I tried opening Storeman from the command line but this doesn't show me the sercrets dialog at all. I also tried using xdg-open but wasn't able to get that to work.

![dialog](https://user-images.githubusercontent.com/7882334/101238414-c62bbd80-36e8-11eb-8996-ac1f8d791435.png)
[journal_with_dialog.log](https://github.com/mentaljam/harbour-storeman/files/5646766/journal_with_dialog.log)
[journal_no_dialog.log](https://github.com/mentaljam/harbour-storeman/files/5646765/journal_no_dialog.log)

**Comment by mentaljam** [comment]
Hi,

Do you still face the issue? If yes, can you, please, try to remove Storeman secrets database?

```sh
devel-su rm .local/share/system/privileged/Secrets/org.sailfishos.secrets.plugin.encryptedstorage.sqlcipher/storeman.db*
```

Then restart the secrets daemon or just reboot.

**Comment by hetas** [comment]
I haven't run into this issue for a while.

**Comment by mentaljam** [comment]
Then I close it for now. Please reopen it if the issue returns.
