### ISSUE TITLE
Behavior of "Search on OpenRepos.net" at the installed apps

### ISSUE THREAD

**Issue by martonmiklos** [mentaljam/harbour-storeman#138]
Hello folks,

In the installed apps list there is a "Search on openrepos"  long tap menu item. 
By selecting it the app jumps to the search page where the application name is pre-filled. 
However some apps have localised application name, which leading to zero search results. (For e.g. slava's counter app has localized "Számláló" name). I am wondering if it would be better to search for the application title (harbour-counter in my example). Or use it as a fallback if no results found for the application name.

The use case where I find this more inconvenient is the following: 
When I got notification about the available updates I would like to check the changelog before installing, so I would like to get to the app page quickly.  I was wondering if it would be useful to have a direct link to the app page where the updated version is found in this menu.

**Comment by mentaljam** [comment]
Hi,

Thank you for the report!

> I was wondering if it would be useful to have a direct link to the app page where the updated version is found in this menu.

Sorry, there is no way to open the package page directly because it's unknown if this particular package is installed from OpenRepos. Also some packages are available at several OpenRepos repositories at the same time.

So I suppose the best solution is to search by the unlocalized name of the package.

**Comment by martonmiklos** [comment]
> Sorry, there is no way to open the package page directly because it's unknown if this particular package is installed from OpenRepos. Also some packages are available at several OpenRepos repositories at the same time.
> 
> So I suppose the best solution is to search by the unlocalized name of the package.

Ah that's makes sense. In this case I agree that the unlocalised name will yield better results in some cases.
