### ISSUE TITLE
Can't create a backup

### ISSUE THREAD

**Issue by mentaljam** [mentaljam/harbour-storeman#142]
https://openrepos.net/comment/36975#comment-36975

**Comment by Adurol** [comment]
I can confirm the issue, but only if I want to backup my bookmarks.

To reproduce, in Backups select the options:
* Repositories -> works
* Installed applications -> works
* Bookmarks -> Storeman crashes

When it works, the ini file is created and looks how it should be. The sections `[package]` and/or `[repos]` are present. I did not verify if importing a backup works.

> Sony Xperia XA2, SailfishOS 4.1.0.24, Storeman 0.2.7

**Comment by mentaljam** [comment]
@Adurol thank you for the tip!
