### ISSUE TITLE
[Feature request] Enable Storeman to open web links in comments

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-storeman#15]
While Storeman 0.0.11 is displaying web links embedded in comments nicely, I am not able to open them from there.

Hence please enable Storeman to open web links (embedded in comments) with the system's default browser. 

P.S.: Sorry about testing Storeman's comment handling so intensively, I just love this functionality (which Warehouse lacks).

**Comment by mentaljam** [comment]
They are already being opened  with the system browser except links to comments. Such links cause navigation of the comments view.

**Comment by Olf0** [comment]
Oops, my bad, should have better looked twice before filing an issue.  Sorry about that.

**Comment by mentaljam** [comment]
It's ok)
