### ISSUE TITLE
order by date-of-last-update

### ISSUE THREAD

**Issue by roman-neuhauser** [mentaljam/harbour-storeman#153]
i'd like to be able to sort app listings by date of latest release.  this is motivated by the fact that there's a lot of software in OpenRepos that is doesn't work in SFOS 4.x, and I use the date as a proxy for estimating whether the software might work for me or if it's probably incompatible.

**Comment by roman-neuhauser** [comment]
but that's across categories / tags, isn't it?  i want *any* app listing sortable in this way: category listing, apps-with-a-tag listing, search results.  it doesn't have to be the default sort order, and it shouldn't be the only one possible, but it should be an option.

**Comment by mentaljam** [comment]
Now I understood. Anyway it's an API issue. We can add a sort proxy to Storeman package models but this would require to load all packages to every model before sorting which means a higher network usage
