### ISSUE TITLE
display only apps for selected architecture / OS version

### ISSUE THREAD

**Issue by roman-neuhauser** [mentaljam/harbour-storeman#154]
this might be two separate tickets, one for $arch, one for $version.  let me know if you want them separated.

when I'm looking for software to install on an XA2, I don't care for packages targeting eg. aarch64.  i'd like to limit packages displayed in Storeman to those that have a particular architecture enabled, or are noarch.

similarly (this is probably even more of a stretch), when I'm looking for software to install on top of SFOS 4.2, I'd like to see only packages targeting this version.  first approximation would be something like "does the package build successfully for the given arch/osversion combination", cf. project -> repositories and package -> build results in the buildservice.  Example:

* https://build.opensuse.org/repositories/home:roman-neuhauser
* https://build.opensuse.org/package/show/home:roman-neuhauser/fake

**Comment by mentaljam** [comment]
This [question](https://openrepos.net/comment/37821#comment-37821) was asked earlier at OpenRepos. You can read [my answer](https://openrepos.net/comment/37825#comment-37825).

Long story short: It should be implemented on the API side.

Filtering by OS version is even harder to implement as RMP should be checked somehow in terms of satisfying dependencies.
