### ISSUE TITLE
[Feature request] Add buttons for <p>, <code>, <blockquote>, <ul>, <ol> and <br /> when writing comments

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-storeman#17]
Please add buttons for  \<p\>, \<code\>, \<blockquote\>, \<ul\>, \<ol\> and \<br \/\> (in addition to the existing five), when writing / editing comments, as these also work well in both, Storeman 0.0.12 and OpenRepos' web-frontend.

Ideas:
- \[¶\] button (codepoint U+00B6 or a uppercase "P") inserts \<p\>\_\<\/p\> 
- \[**c**\] button (bold lowercase "c") inserts \<code\>\_\<\/code\>
- \[\> \] button (greater sign, maybe followed by a space) inserts \<blockquote\>\<p\>\_\<\/p\>\<\/blockquote\> 
- \[• \] button (codepoint U+2022 or a bold U+00B7, maybe followed by a space) inserts \<ul\>\<li\>\_\<\/li\>\<\/ul\>
- \[1.\] button inserts \<ol\>\<li\>\_\<\/li\>\<\/ol\>
- \[CR\] button inserts \<br \/>_   (***Edit:*** Not really needed, as \<br \/\> is inserted on submission of a comment at every line break.)

Notes:
- "_" denotes the cursor position after pressing the corresponding button. 
- It may make sense to reorder the buttons, e.g. \[**B**\] \[*I*\] \[U\] \[**c**\] \[M\] \[¶\] \[\> \] \[• \] \[1.\] \[🔗\]

**Comment by mentaljam** [comment]
The <p> and <br /> tags are not really needed as they are inserted automatically by OpenRepos.

And it's a question about the list tags. A list tag assumes that there are more than one list items inside it. So you insert a pair <ol> or <ul> tags and a pair of <li> tags inside it and what about next items? Add one more button for the <li> tag? Or try to detect if the cursor is inside list tags and insert list items tags on return press like in WYSIWYG editors?

**Comment by Olf0** [comment]
> The `<p>` and `<br />` tags are not really needed as they are inserted automatically by OpenRepos.

While I fully agree WRT the `<br />` tag, paragraphs (`<p>`) are really hard to control properly.  I found setting paragraphs explicitly (in both, Storeman and the "plain text editor" in OpenRepos' web-frontend) necessary many times. 
Somehow the behaviour with Storeman and OpenRepos' "plain text editor" appears to be slightly different: When using Storeman 0.0.12 often a `<br />` is inserted, where I would have expected a `<p></p>`. 
Also note that OpenRepos' web-frontend automatically inserts a `<p>`_`</p>`, when one starts with an empty message.  This may cause some of the perceived differences in behaviour. 

> And it's a question about the list tags. A list tag assumes that there are more than one list items inside it. 

Well, as you chose to let users edit raw, HTML formatted commets (which is good IMHO, as easier to implement and providing the user with full control), users have to have some basic knowledge about HTML when using these tag-buttons.  (Users without such knowledge can still just type a message and it will be automatically formatted by OpenRepos, when submitted.  Only when these users try to edit a comment, they will have trouble understanding what happened to their message.)

In short: For editing raw HTML, one has to have some basic knowledge about HTML, anyway. 

This is why I regard the buttons as little helpers to insert supported tags easily (i.e. without having to type them), but not more than that. 

> So you insert a pair <ol> or <ul> tags and a pair of <li> tags inside it and what about next items? Add one more button for the <li> tag? 

I considered suggesting this yesterday, but did not have an idea for a symbol (and thought one may just cut&paste the inserted `<li></li>`). 

Thinking about it again, an extra button absolutely makes sense.  You may use \[· \] (codepoint U+00B7) for `<li></li>`, while \[• \] (codepoint U+2022) for `<ul><li></li></ul>`, and order these buttons \[• \] \[1.\] \[· \]

> Or try to detect if the cursor is inside list tags and insert list items tags on return press like in WYSIWYG editors?

IMHO, no: Once you start parsing HTML and try to react accordingly, things become complicated (e.g. multiple levels of nested tags) and you started the route to an full WYSIWYG editor (initially still rendering raw HTML). 
IMO, you may consider this route as a separate WYSIWYG ("rich text editor") mode much later; for now the existing solution (editing raw HTML with helper buttons) is absolutely fine.

**Comment by mentaljam** [comment]
> paragraphs `<p>` are really hard to control properly

>  I found setting paragraphs explicitly ... necessary many times

As said on the [manual page](https://openrepos.net/filter/tips) to insert a paragraph you should add an empty line just like here on GitHub. If you want to insert just a line break then start to type from a new line. Look at my screenshots:

### This is how I've typed text
![This is how I've typed text](https://user-images.githubusercontent.com/6236802/28998377-16e9313e-7a32-11e7-8046-f82e79d6279e.png)

### And this is how it was composed by OpenRepos
![And this is how it was parsed by OpenRepos](https://user-images.githubusercontent.com/6236802/28998378-32cd038a-7a32-11e7-875d-ed8da570a42c.png)

**Comment by Olf0** [comment]
Yeah, I know. 
While simple cases (as yours above) are working well, I regularly run into trouble when there are already a couple of tags (i.e. while editing comments).  I have the impression there is something wrong with the automatic tag insertion when submitting comments to OpenRepos (mostly with OpenRepos' web-frontend, as I am using this for years, but seemingly also with Storeman 0.0.12).  But I have never completely understood this phenomenon (i.e. the mechanisms behind it), otherwise I would know how to avoid it and / or be able to file a comprehensive issue description. 

P.S.: This is why I ended up writing "plain text" formatted comments in OpenRepos' web-frontend (i.e. *not* HTML formatted ones using the "plain text editor"), when no markup, links etc. are needed.  But it is  extremely tedious to change that (to filtered HTML format) later on, this is where Storeman comes very handy, now.

**Comment by Olf0** [comment]
Hmmm, I don't know if I should close this issue, as all major points raised in this issue are addressed in Storeman 0.0.13. 
So I leave that up to you, how to proceed with the remaining points (e.g. defining them as irrelevant, hence closing this issue). 

P.S.: 
`foo`<br\ >
`bar

foobar`

becomes

`<p>foo<br />`<br />
`bar</p>`<br />
`<p>foobar</p>`

becomes 

`<p>foo<br />`<br />
`bar<br />`<br />
`foobar</p>`

just by hitting "Edit", and then "Send" each time.  After that (with only a single paragraph left), it stays the same.

**Comment by Olf0** [comment]
Sorry, I forgot about this issue.
Closing this, as this is working very well for most edits of existing comments, and supposedly is not an issue of Storeman, anyway.
Actually, I have the impression that this is improved already (both, in OpenRepos web-frontend and Storeman using its web API), but currently lack the time to properly test this. 

But much more importantly than this: Storeman has become so nice, overall and the comment function specifically.

Thank you so much for your efforts, the result is really impressive.
