### ISSUE TITLE
Storeman backup.

### ISSUE THREAD

**Issue by CaptainKhan** [mentaljam/harbour-storeman#24]
I created two backups in Storeman on my Intex Aquafish 2.1.0.11 SFOS and they showed up in My Device when i logged into open repos.

I had to reset the device and reinstall SFOS 2.1.0.11 afterwards after logging into open repos the two backups i created no longer show and i wasnt able to restore from backup.

**Comment by mentaljam** [comment]
Oh, now I understand that I have to describe the backup process more clearly. Storeman creates backups in your Documents directory so you should copy them somewhere before reset. It does not use OpenRepos for storing your backups.

So I'm afraid you've lost your backups. Sorry((

**Comment by CaptainKhan** [comment]
ahh ok no problem, i can do an internal backup from storeman to SD card Documents.
