### ISSUE TITLE
[Minor usability bug] Storeman displays manually installed RPMs as "available", although not being available in any subscribed repository

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-storeman#28]
I stumbled across this when trying a test version of Patchmanager 2.4.0:
After installing it manually (via `pkcon install-local`) on my "test phone", Storeman 0.0.15-2 displays it as "Installed version" and "Available version", although Patchmanager 2.4.0 is *not* yet available in any subscribed repository.  This is a bit irritating: ![screenshot_20171004_006](https://user-images.githubusercontent.com/16547876/31157799-d1f3e2da-a8bd-11e7-899e-8bd5538d79ee.png)

On my "production phone", where I have the latest release version of Patchmanager2 installed, it looks like this (i.e. O.K.): ![screenshot_20171004_001](https://user-images.githubusercontent.com/16547876/31157729-4766a2c4-a8bd-11e7-99e8-b8766f17c5d0.png)

Expected result: Storeman always displays the latest version of an RPM available in subscribed repositories as "Available version", even if a newer version was installed manually and is correctly displayed as "Installed version".

**Comment by mentaljam** [comment]
Current realisation of package management is quite buggy. I'm in lazy process of refactoring that should fix this issue too. So I leave it open for now.
