### ISSUE TITLE
[Feature suggestion] Add strikeout button in comment function

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-storeman#30]
As the strikeout function has been fixed today in OpenRepos' comments, please add a strikeout button "-S-" in Storeman's comment header, creating the tag pair \<s\>_\</s\>.

As the available space in the current button layout is not sufficient for another button in portrait orientation on a Jolla 1 phone, this suggestion also includes making all buttons in the comment function the same size, which needs a reduction of the font size of the "pre" button and maybe also shrinking the margins and/or font sizes of the "< >" and "🔗" buttons.
Actually I believe that displaying all buttons at the same width/size will look better and more consistent, anyway.

**Comment by Olf0** [comment]
A better idea for reducing the width of the "< >" button (than reducing its font size or margins) is to use a smaller space between the two brackets, e.g. the Unicode code point U+200A "Hair space" (i.e. < >) or U+2009 "Thin space" (i.e. < >) or U+2006 "Six-per-EM space".  Actually the U+200A "Hair space" looks best and most reasonable to me.

**Comment by Olf0** [comment]
Oh, I missed to reason why a strikeout button is needed, IMO:
Strikeout is quite useful when correcting comments which already have follow-up comments, in order not to disrupt the reading flow for others (i.e. not to render the follow-up comments idiotic).

**Comment by mentaljam** [comment]
Hi,
I also think that all buttons should have the same width but I don't know how to show for example the `pre` tag. About the `code` tag - there is no space between brackets at all.

https://github.com/mentaljam/harbour-storeman/blob/dd762bffd51d590419a1abd1ff5aecfe2b4834cb/harbour-storeman/qml/components/CommentField.qml#L157

Also note that the buttons widget is flickable and could be swiped to the left/right. So some buttons could be "hidden" and a hint to swipe could be showed to the user on the first use.

**Comment by Olf0** [comment]
Thanks for your prompt reply and the pointer to the code.  Well, while reading your reply, I thought "Oh", and "Oh, again", as I did neither expect setting the button width to a fixed size and having its content "fit to size" being impossible or being unable to set the font size.
Well _before_ HTML5 the font tag supported a size attribute, e.g. <font face="monospace" size=2>foo</font>, maybe it is worth a try.
Otherwise the only option I see to shrink the oversized "< >", "pre" and "🔗" button content is supposedly to use a different font than monospace.  On first thought, the regular font with "< >" separated by aforementioned hair space (plus maybe in bold) and "pre" set in bold might fit well. 

But as the whole button line is flickable (and I personally use landscape orientation most of the time), a "strikeout" button (preferably inserted between the "underline" and "quote" buttons) seems to be feasible (at least under GUI aspects).
