### ISSUE TITLE
can't post comments

### ISSUE THREAD

**Issue by legacychimera247** [mentaljam/harbour-storeman#34]
the title says it all, if i click on the send button the comment disappear without doing nothing...

**Comment by mentaljam** [comment]
Did you try to relogin?

**Comment by legacychimera247** [comment]
tried and it's working now...thought i've already done that but maybe i am mistaken...

**Comment by mentaljam** [comment]
I think this issue should be opened as it's really a bug. The application should notify you that your authentication has expired but it doesn't work this way.

**Comment by PawelSpoon** [comment]
same.issue here, storeman shows log out, but comment disappered after commit
