### ISSUE TITLE
[Suggestion] Notify users about disabled external apps installation in Sailfish settings

### ISSUE THREAD

**Issue by ElderOrb** [mentaljam/harbour-storeman#43]

**Comment by mentaljam** [comment]
It's a really good idea. I'll look what I can do.

**Comment by mentaljam** [comment]
@ElderOrb, I turned off untrusted sources but I could still add repositories and install apps from the OpenRepos. So I think this option does not affect your issue. May be you have a lot of enabled repositories so it takes a long time to refresh them all?

**Comment by mentaljam** [comment]
Close as this option doesn't affect Storeman.
