### ISSUE TITLE
[Usability issue] Storeman lists the installed versions of upgradeable applications!

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-storeman#44]
Storeman lists the installed versions of upgradeable applications under "Installed Applications --> Update available".
It should rather list the versions of the available updates there (i.e. the versions these applications are upgradable to, like Warehouse does).

But even nicer would be to state both, the installed and the available, updated version numbers, e.g.:
    _mapboxgl-qml_
    _1.12-10.31.1.jolla ➟ 1.20-10.34.1.jolla_

Side note: Unicode codepoints 2192 ( → ), and 279C to 27A1 ( ➜ ➝ ➞ ➟ ➠ ➡ ) seem to be appropriate arrows.

Tested with Storeman 0.0.20 and 0.0.19 on Jolla 1 phones under SFOS 2.1.4.14 and 2.1.3.7.

P.S.: May I also suggest changing the header line from "Update available" to "Available Updates", IMO that fits better.

**Comment by Olf0** [comment]
Thanks, this is looking really nice in Storeman 0.0.30!

BTW, a reason for me to suggest increasing the version number significantly, again. ;)
Having used and looking thoroughly at Storeman for long, I would call it in very late beta stage by now, hence warranting a version number of 0.8.x or 0.9.x.

**Comment by mentaljam** [comment]
For now Storeman has some significant issues concerning resolving versions of packages. Increasing version above 0.0.X means stabilization of source code which is not true due to those issues. When I solve them and when I find Storeman stable enough I'll increase the version up to 1.0.0.

**Comment by Olf0** [comment]
> For now Storeman has some significant issues concerning resolving versions of packages.

I know, but that is hardly and rarely apparent to users.
And Storeman has a many thousands users, obviously not having significant troubles with Storeman.

> Increasing version above 0.0.X means stabilization of source code which is not true due to those issues. 

No, it does not mean thatthat, at least not according to [Semantic versioningversioning](https://semver.org/).

> When I solve them and when I find Storeman stable enough I'll increase the version up to 1.0.0.

Oh, that will be a large, sudden jump nobody will be able to understand.
