### ISSUE TITLE
Repository with underscore '_' in name

### ISSUE THREAD

**Issue by DrYak** [mentaljam/harbour-storeman#53]
Currently, Storeman simply uses the 'search' function when listing repositories.

The problem is that openrepos.net fails to search if there is an underscore in the name such as Steffen Förster (authors of CodeReader)'s [steffen_f](https://openrepos.net/search/node/steffen_f) (NOTE: It still works correctly if [specifically search for users](https://openrepos.net/search/user/steffen_f)).

So Storeman fails to display any content for such situations.

Do you think it would be possible to modify storeman so it doesn't fail ?

e.g.: relying on openrepos.net's "search for users"
or libzypp's "search by repos" ?

**Comment by mentaljam** [comment]
OpenRepos doesn't provide any API methods for special search for users (at least there are no documented methods). However you can post an issue [here](https://github.com/custodian/orn-core/issues).

Also please clarify about  _libzypp's "search by repos"_.

**Comment by DrYak** [comment]
> Also please clarify about *libzypp's "search by repos"*.

Zypp, the engine used by both `zypper` and PackageKit's back-end on Sailfish OS can search a list of packages by repositories.
I'm not very familar with the PackageKit DBUS interface, but on the command line, with `zypper` :

    zypper packages --repos openrepos-Dax

...will list you all the packages present in repository *openrepos-Dax*

There should be a way to do something similar using PackageKit and `get-packages` with some filter.

**Comment by mentaljam** [comment]
But it doesn't solve the issue with searching for users. For now one can get a list of packages of a publisher by tapping on the `More by ...` button on the Application page.

**Comment by DrYak** [comment]
Oh, didn't notice the `More by ...` button worked with underscore.

Maybe, then, would it be possible to leverage *that* to search by repositories from the storeman menu ?
(Instead of the current "redirect to search function", which currently fails for repos with underscores, and adds tons of irrelevant search results whenever the same word is used elsewhere)
That would be great.

**Comment by mentaljam** [comment]
I'm afraid it couldn't be done. This button just loads all the packages of the author by his numeric ID using the OpenRepos API. It can't search by keywords.
