### ISSUE TITLE
it's impossible to send a comment

### ISSUE THREAD

**Issue by atlochowski** [mentaljam/harbour-storeman#55]
in tje newest version of storeman it's impossible to send a comment. after pushing send button content of comment disapearing.

**Comment by mentaljam** [comment]
It's not the first time I've received such a report. It seems that Storeman doesn't handle the authentication status in proper way. As a workaround I can suggest you to re-login to OpenRepos.net.

**Comment by atlochowski** [comment]
after re-login it's ok. thanks

**Comment by Olf0** [comment]
I can confirm this to happen still, every now and then, but logging out and back in to OpenRepos always resolves this issue with recent Storeman versions.

@mentaljam, thanks for putting so much effort into this, the stepwise announcements "Authorization is going to expire." and " Authorization expired!" are really nice.
But sometimes Storeman still shows being logged in to OpenRepos, although writing a comment fails (so being logged in did not seem to be true).

As this issue appears to be a hard one, a way to alleviate it would be to preserve the written text in the comment field, when submitting a comment fails.
Currently it is extremely frustrating, that the freshly written comment is gone, when this issue hits.

**Comment by Pohli** [comment]
Yes, I ran into exactly the same problem and I absolutely share Olf0s comment.
