### ISSUE TITLE
Missing option to add a custom/personal repository

### ISSUE THREAD

**Issue by rebos** [mentaljam/harbour-storeman#56]
I need to enable a custom/personal repository to install a specific app. Within "Storeman" settings I see one existing repository enabled which is called "basil". Via localized pulley menu I have four options which I would translate to "Update", "Update Cache", "Deactivate all" and "Remove all".

I expect an option to add a repository next to the mentioned options - but there is no such option.

Details on my environment: Storeman 0.0.25, SailfishOS 2.1.4.14 (Lapuanjoki), device "Jolla Phone", installation of 3rd party apps is enabled.

**Comment by mentaljam** [comment]
You can add a repository with the pulley menu on the app page. Storeman is an OpenRepos.net client so it works with these repositories. If you need to add a custom repository you can use the Terminal app:

    devel-su ssu ar <repo> [url]

To read more about ssu commands run `ssu` without arguments.

**Comment by rebos** [comment]
Thank you for the quick reply! I would like to use the pulley menu rather than the command line tool. Just to be sure that we are talking about the same "pulley menu on the app page" I attached a screenshot showing "my way" to that menu. Is this the menu, you think of, or am I missunderstading you?

![screenshot-steps](https://user-images.githubusercontent.com/490798/40383951-78deff72-5e02-11e8-803d-a835670b7ecf.png)

**Comment by mentaljam** [comment]
Nope, I'm talking about another page :) Open the page of the application you want to install (from the "Recently updated" for example) and then pull down the menu.

![_ _20180522_001](https://user-images.githubusercontent.com/6236802/40384847-73320258-5e0d-11e8-809e-58322abd26f1.png)

**Comment by rebos** [comment]
Thank you very much for your explanation! It helped me to understand the process of adding repositories within "Storeman". Now I was able to add the custom/personal repository, that the app I actually wanted to install, needed for resolving dependencies.
