### ISSUE TITLE
Open Storeman from other app

### ISSUE THREAD

**Issue by fravaccaro** [mentaljam/harbour-storeman#68]
Good evening and thank you for your work for Storeman.

I'd like to link it to my UI Themer to make easier to find new themes.

In a nutshell, clicking on a menu would open Storeman with the result page for a particular tag search.

Is it possible somehow?

Br,

Francesco

**Comment by fravaccaro** [comment]
I tried to follow your directions but I'm a bit lost. Would you mind giving here an hint?

I got here in my qml page (I've imported `Nemo.DBus 2.0`)

```
    DBusInterface {
        id: openStore
         service: 'harbour.storeman.service'
         path: '/harbour/storeman/service'
         iface: 'harbour.storeman.service'

         signalsEnabled: true

         function openPage() {
             call('initialSearch', themepack)
         }

     }
```

and I trigger it with

`        MenuItem { text: qsTr("Download more themes"); onClicked: openStore.openPage() }`

but when I run the Item I get

```
[W] unknown:0 - QDBusMarshaller: type `QObject*' (39) is not registered with D-BUS. Use qDBusRegisterMetaType to register it
[W] unknown:0 - QDBusConnection: error: could not send message to service "harbour.storeman.service" path "/harbour/storeman/service" interface "harbour.storeman.service" member "initialSearch": Marshalling failed: Unregistered type QObject* passed in arguments
[W] unknown:75 - file:///usr/share/sailfishos-uithemer/qml/components/themepacklistview/ThemePackListView.qml:75:5: QML DBusInterface: QDBusError("org.freedesktop.DBus.Error.Failed", "Marshalling failed: Unregistered type QObject* passed in arguments")


```

**Comment by mentaljam** [comment]
Sorry for a late reply. If it's still actual, your interface should look like this

```qml
DBusInterface {
    id: openStore
    service: 'harbour.storeman.service'
    path: '/harbour/storeman/service'
    iface: 'harbour.storeman.service'
    
    function openPage() {
        call('openPage', ['SearchPage', {initialSearch: 'theme'}])
    }
}
```

If you call `openPage` in one place then there is no need to define it as a function - just call 

```qml
openStore.call('openPage', ['SearchPage', {initialSearch: 'theme'}])
```

where necessary.

**Comment by fravaccaro** [comment]
No need to apologize :) Thank you so much for your help, it works like a charm!
