### ISSUE TITLE
[Minor usability enhancement] Visual indicator for leaving the "Rating" sub-window

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-storeman#74]
This is a really minor, visual usability issue (but supposedly easy to fix, too):

While Storeman's "Rating" sub-window is easily exited by swiping in any direction (left, right, up or down) or tapping anywhere on the screen off the stars, currently Storeman lacks a visual indication how to leave this sub-window (in contrast to all other sub-windows in Storeman).

Hence please display the white ¾ circle in the upper right corner of the screen in the "Rating" sub-window, too.

**Comment by mentaljam** [comment]
The white circle indicates that one can navigate back on the page stack. In general this overlay is complies the Silica UX and I don't think anything should be changed.

**Comment by Olf0** [comment]
Your statements would make perfect sense (an I would 100%tested agree with themthem), **if** Storeman displaydisplays that "white circle" in the "Rating" window.
But it does not (regardless of the device orientation etc.):
![screenshot_20181122_002](https://user-images.githubusercontent.com/16547876/48970650-34741a80-f00f-11e8-9778-5700163564da.png)

Hence this issue is about **adding** the "white circle" exit indicator to this window (i.e. not asking for removing something non-existent).

**Comment by mentaljam** [comment]
This is not a page on the stack so the back indicator (white circle) should not be shown. It's an overlay like the link actions in the stock web-browser (which is shown on a long tap on a link).

**Comment by Olf0** [comment]
The fact that the "Rating" sub-page is implemented differently than other sub-pages in Storeman should IMO **not** result in a different user experience with this page.
Exactly in line with your statement:
> The white circle indicates that one can navigate back on the page stack. In general this overlay is complies the Silica UX [...]

Now that I comprehend that you would need to emulate that button somehow on the "Rating" page to achieve a consistent user-experience throughout **all** Storeman sub-pages, I can well understand if you close this as "Won't fix" and leave the question how to get out if the "Rating" sub-page up to Storeman's users (as they **will** succeed on their first try).
Still I wholeheartedly disagree with defining this as a non-issue.  As I wrote in the issue title this constitutes a "Minor usability enhancement", not a technical issue (hence technical reasons IMO may result in "Won't fix, too much work with only little gain", but not on dismissing this usability issue).

**Comment by mentaljam** [comment]
> The fact that the "Rating" sub-page is implemented differently than other sub-pages

It's not a sub-page, it's an overlay. So no navigation elements are required here. I understand your idea that one may be confused how to close the rating overlay but I haven't received any comments on it. And I guess users have no troubles with closing the overlay because it complies the Silica UX.

Sorry but I'm closing this issue.
