### ISSUE TITLE
[Usability issue] "Network error" notification, even though everything is fine

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-storeman#82]
Storeman shows a "Network error" notification on the top of the screen, when started.  After that everything works fine (if there is no real network problem).
The "funny" thing is, this usability issue only occurs on one of my Jolla 1 phones (this runs SFOS 2.2.1), while on another Jolla 1 (also with SFOS 2.2.1) and an Xperia X (with SFOS 3.0.0) that does not happen.  But on the Jolla 1 phone affected, it happens on every start of Storeman.

I would not have bothered to file this issue (assuming it is caused by a local misconfiguration), if not [@monkeyisland reported a similar issue at OpenRepos](https://openrepos.net/comment/27393#comment-27393).  Although @monkyisland reports it to happen when entering the bookmarks (on a Jolla 1 phone with SFOS 3.0.1.11), which always works on my affected Jolla 1 phone. 

Tested with Storeman 0.0.32 and I guess this is the first version with which this issue occurred (not sure though, as there have been many Storeman releases in November: 0.0.29, 0.0.30, 0.0.31 and 0.0.32).

P.S.: This is definitely different than issues #37 and #50, `connmanctl state` outputs `State = online`.
P.P.S.: Screenshot
![screenshot_20190115_001](https://user-images.githubusercontent.com/16547876/51210942-5ce40b00-1914-11e9-81f2-4a50cd6d13aa.png)

**Comment by Olf0** [comment]
Oh, exactly this issue has been reported by [@mick at OpenRepos](https://openrepos.net/comment/26937#comment-26937), supposedly also with Storeman 0.0.32, but SFOS 3.0.0.8 on an Xperia X.

**Comment by mentaljam** [comment]
I also face this issue randomly on my Jolla 1. I think it's because of the "new" mechanism of handling errors.

**Comment by jgibbon** [comment]
I had a few "Network errors" a while ago after an openrepos repository was deleted and storeman tried to update it… I think it may have been after Markkyboy deleted all his stuff…https://openrepos.net/user/1290/programs
Perhaps this has something to do with it?

cheers!

**Comment by mentaljam** [comment]
@jgibbon I added Markkyboy's repo manually, refreshed it with Storeman and there were no errors. Do you remember on what page of Storeman you had the error notifications?

**Comment by jgibbon** [comment]
Oh, I may have misinterpreted this, then. 
The error appeared, _as far as I remember_, when opening Storeman or manually refreshing package lists.

**Comment by mentaljam** [comment]
Could someone please try the [dev version](https://build.merproject.org/package/repositories/home:mentaljam/harbour-storeman-dev) and check if there is still an issue with error notification?

**Comment by Olf0** [comment]
That is [harbour-storeman-0.0.33-1.24.1.jolla.armv7hl.rpm](https://build.merproject.org/package/binary/home:mentaljam/harbour-storeman-dev?arch=armv8el&filename=harbour-storeman-0.0.33-1.24.1.jolla.armv7hl.rpm&repository=sailfish_latest_armv7hl) at the moment, correct?

I hope to find some time tonight, but unfortunately my two Jolla 1 phones switched behaviour: Storeman 0.33-3 stopped emitting "Network error!" on the phone where it first appeared, but continues to do so on my "production phone".  My Xperia X still has not exhibited this issue.
So it is a little hard to obtain a conclusive test result, as this issue seems to come and go even without deliberate changes.

**Comment by mentaljam** [comment]
Can you please start Storeman from terminal:

```bash
harbour-storeman
```

and see if there are any warnings concerning networking?

**Comment by Olf0** [comment]
Yes:
* I went back to Storeman 0.0.33-3, because this is my production phone (but currently the only one permanently exhibiting this issue).<br />
  If you want me to test Storeman 0.0.33-1.24.1 at the command line, please let me know.
* Yes, there is a network related error upon each start of Storeman 0.0.33-3:<br />
  `[W] unknown:0 - Network request error QNetworkReply::NetworkError(ContentOperationNotPermittedError) - "Error transferring https://openrepos.net/api/v1/session - server replied: : Access denied for user anonymous"`
* While this warning is consistently displayed in consecutive tests, on the first test I was confronted with multiple "Authentication error" notifications.  No idea, if this was related to this issue or not, but it did not happen on any later test, although I did not reauthenticate my user account for OpenRepos or did anything else but starting and stopping Storeman.

**Comment by mentaljam** [comment]
The "Authentication error" comes from launching Storeman from command line. Normally it's launched by the invoker which grants access rights to operations with packages. So just ignore it.

Nevertheless the warning you have caught points the direction for further investigations :+1:

**Comment by Olf0** [comment]
BTW:
* Cross checked on the other Jolla 1 (which stopped displaying "Network error" a few weeks ago): It does not show this warning when Storeman is started at the command line (as expected), while all other output at the command line is exactly the same.
* Thanks for the info that the "Authentication error" notifications are related to pkcon / libzypp (and hence unrelated the this issue).

**Comment by mentaljam** [comment]
I think I found the reason of repeating this notification:
- Your user session expired
- Storeman offered you to re-login
- You closed Storeman without re-login
- On next start Storeman started to show this notification

The problem was in bad storing of session data. Now after session expiry Storeman clears its data and doesn't show this annoying notification.

Can you please try once again the [OBS build](https://build.merproject.org/package/binaries/home:mentaljam/harbour-storeman-dev?repository=sailfish_latest_armv7hl)?

**Comment by Olf0** [comment]
Sorry, Storeman 0.33-1.25.1 shows exactly the same behavior, at the command line and at the GUI, before and after a reboot.

BTW, on little thing in your description I do not concur with:
> * Storeman offered you to re-login
> * You closed Storeman without re-login
I usually reauthorise myself immediately when Storeman informs me to do so.
But I have the impression that Storeman still sometimes looses the user authorisation at OpenRepos without noticing it (that may even be unavoidable with OpenRepos' current API behavior.

**Comment by Olf0** [comment]
> Try to logout and login again.

Did that, **after** updating from 0.0.33-3 (I am reverting to it after testing) to 0.0.32-1.25.1 again.
1. Storeman started at the command line did not seem to like trying to log out from OpenRepos: my avatar picture and status "Logged in as olf" was still shown, despite trying to log out three times.
2. Closing Storeman and staring it at the GUI resulted in Storeman continuously displaying the "waiting circle" on its main page.
3. So I rebooted, started Storeman (still 0.0.33-1.25.1) at the GUI: Now I was logged out of OpenRepos, being able to log in and ... no "Network error" upon a restart of Storeman at the GUI. 
4. So I closed Storeman and started it from the command line.  Now a new warning is emitted each time:
`[W] unknown:461 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/PulleyMenuBase.qml:461:13: QML State: Binding loop detected for property "when"`
5. Sometimes another warning is additionally displayed:
`[W] unknown:-1 - <Unknown File>: QML StateGroup: Can't apply a state change as part of a state definition.`
6. Once I also saw a `[W] unknown:0 - libpng warning: iCCP: known incorrect sRGB profile`, but cannot reproduce it.

**Comment by Olf0** [comment]
> I've added a temporary code that should stop showing these notifications in your case.

I do not fully understand all the things the QML code added in commit 30d7449 does, but permanently storing ones user name at OpenRepos is actually a general usability improvement, IMO.  I did not care to file this as an issue here yet, because it is rather minor, but currently it is annoying to have to type in ones user name again, each time one misses to hit Storeman's notification to reauthorise.
 
> Please try the new one version from OBS :)

You are too quick for me. 😉
More seriously:
* I know I am your only tester for this issue, currently.  Still my time is limited, especially on weekdays.
* Editing comments here at Github does not repost them per email.  Hence edits should be limited to corrections and clarifications, but not comprise added information (I regularly fail to adhere to this rule).
Consequently I did my testing earlier this night with 0.0.33-1.25.1, as I checked email, but not this web page.

I **may** take a look at the new build in the next couple of days.
But actually I am more concerned about the reproducibility of steps 1. and 2. in [my previous comment](https://github.com/mentaljam/harbour-storeman/issues/82#issuecomment-460484464): I only tried that once, yet (as it needs reinstalling 0.0.33-3 and then 0.0.33-1.2x.y again).

**Comment by Olf0** [comment]
The warning in step 5. of [my previous comment](https://github.com/mentaljam/harbour-storeman/issues/82#issuecomment-460484464) is emitted when entering "This device" in Storeman's top menu.

**Comment by Olf0** [comment]
Logging out and back in at OpenRepos in Storeman 0.0.33-1.25.1 takes two tries:
1. Logging in fails.
2. Logging in succeeds, but Storeman emits a notification at the GUI, that the login at OpenRepos failed (which was not displayed in step 1., but looks like the message from there).

Output at the command line, covering both steps above:

> [W] unknown:38 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/Util.js:38: TypeError: Cannot read property 'parent' of null
[W] unknown:38 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/Util.js:38: TypeError: Cannot read property 'parent' of null
[W] unknown:0 - Network request errorerror QNetworkReply::NetworkError(AuthenticationRequiredError) - "Host requiresrequires authentication"

**Comment by mentaljam** [comment]
Reply to https://github.com/mentaljam/harbour-storeman/issues/82#issuecomment-460484464

Points 5 and 6 seem to concern Silica bugs. Point 7 concerns icons that are loaded from OpenRepos.net (it's not critical).

Reply to https://github.com/mentaljam/harbour-storeman/issues/82#issuecomment-460491539

This commit adds the code that adapts the old configuration to the new one. In fact it just logs you out to rewrite the configuration on next login. Quite a dirty thing but it occurs once after update.

Reply to https://github.com/mentaljam/harbour-storeman/issues/82#issuecomment-460494712

It's strange. I have logged out and in for dozens of times without any error while was testing.

**Comment by Olf0** [comment]
WRT:
* Points 5 & 6: O.K.
* Point 7: Already assumed that, fine then.
* Your explanation, what commit 30d7449 does: Thanks, that might help me to better understand what is happening while testing.
* Points 1 & 2:
  As usual I went back to Storeman 0.0.33-3 after the last round of tests with 0.0.33-1.25.1.
  Tonight I wanted to retest with Storeman 0.0.33-1.26.1, but now Storeman 0.0.33-3 does not show a "Network error" when started (I tried a couple of times starting at the GUI and command line, plus rebooted once in between), anymore.
  AFAIU, Storeman 0.0.33-1.25.1 did not alter the configuration file (commit 30d7449 was for 0.0.33-1.26.1, right?), so I assume that deleting `~/.config/harbour-storeman/harbour-storeman.conf` would not help restoring the old state (with "Network error" on startup), correct?

How shall I proceed?
Just updating to Storeman 0.0.33-1.26.1 and checking I cannot reproduce this issue anymore?  But I cannot reproduce it anymore, already. :\

**Comment by mentaljam** [comment]
To reproduce this issue on 0.0.33-3 from OpenRepos.net:
- log in
- close Storeman
- open `~/.config/harbour-storeman/harbour-storeman.conf` in any text editor
- change the value of `user/token` inside `@ByteArray()` (make it invalid)
- open Storeman

After these steps you should see "Network error" on startup. It's happening because in fact you're not logged in (the token is invalid) but Storeman thinks you are.

If you then update to Storeman from OBS it will (I hope) clear invalid token and other data from the `user` section of the config except the username to make it easier to log in next time.

**Comment by mentaljam** [comment]
@Olf0 shame on me! I just realized that OBS didn't update sources before building storeman-dev. I've uploaded a fresh [RPM](https://github.com/mentaljam/harbour-storeman/releases/download/v0.1-rc1/harbour-storeman-0.0.33-3.armv7hl.rpm) built with SDK here on GitHub.

**Comment by Olf0** [comment]
Thanks, now understand what is going on, even without understanding the QML code.
And you seem to be quite sure to have fixed this issue. 
Checking:
> To reproduce this issue on 0.0.33-3 from OpenRepos.net: [...]

Nice, this allows me to use my testing phone for the final test.
* Altered a single character of the cookie hash in `~/.config/harbour-storeman/harbour-storeman.conf`.
* Started Storeman at the command line.
  * A warning "Network error" is emitted at the command line.
  * A "Reauthorize at OpenRepos" notification is displayed at the GUI, likely obstructing the "Network error" message there.
* Hence starting a second time at the command line: "Network error" there and at the GUI.

Great, now this issue is fully reproducible for me. 🙌
> I've uploaded a fresh RPM built with SDK here on GitHub.
* Downloaded and installed it per `pkcon install-local`.
* Starting Storeman at the command line:
  * No "Network error" at the command line and GUI.
  * No warnings #5 (Silica) and #6 (QML state) at the command line.
    Just curious: did you suppress them or are they really gone (this is a different Jolla 1 phone than the one used in former tests of this issue)?
  * New GUI: nice, although I have to get used to it (I had no issues with the old GUI, hence this is a change I have adapt to without gaining anything; but this is a very personal perspective, the new GUI is definitely better for new users).

Observations:
* When Storeman was already started and closed at least once since last reboot of the device, v0.0.33-3 from Github emits `[W] unknown:0 - OrnRecentAppsModel(0xdeadbeef) Model is already fetching data` at the command line **twice**.
v0.0.33-3 from OpenRepos always did that only once.
* When started the second time, Storeman 0.0.33-3 from Github becomes stuck in an endless loop emitting "*An error occurred* Click to view details" notifications right after startup.
When tapping on one such notification an error page is opened, displaying "*An error occurred* Failed to obtain authentication.".
* I first attributed this to accidentally altering the cookie value instead of the token value.
But it also happens (or persists?) when altering the token value.
* This behavior persists over a reboot.  I will continue to experiment, what exactly causes this, how to revert to a working state and how to trigger it again.

**Comment by Olf0** [comment]
Experiments with Storeman 0.0.33-3 from Github:
* Putting back an originally working configuration file from v0.0.33-3-OpenRepos lets v0.0.33-3-Github work fine.
* Using an configuration file with an altered / broken token value now results in v0.0.33-3-Github entering the "*An error occurred*" loop on this first try.

**Comment by Olf0** [comment]
So I started at the beginning, again:
* Reverted to Storeman 0.0.33-3-OpenRepos and its original, working configuration file: Endless loops of "*An error occurred*" notifications!
* Rebooted: Now Storeman 0.0.33-3-OpenRepos is working fine.
* Using a configuration file with an altered / broken **token**, Storeman 0.0.33-3-OpenRepos emits no "Network error", but enters the endless "*An error occurred *" loop, again.
* Rebooted, using a configuration file with an altered / broken **cookie**:
  * First start of Storeman 0.0.33-3-OpenRepos: "Network error" at the command line, "Authorization required" notification at the GUI.  No refreshing of repositories, as the time threshold was not reached, yet.
  Manually triggered refreshing the repos (*This device -> Repositories -> Refresh cache*): Storeman 0.0.33-3-OpenRepos enters the "*An error occurred*" loop.
  * Second start: "Network error" at the command line, entering the "*An error occurred*" loop immediately.

Conclusions so far:
* Storeman 0.33-3 (no matter which version) is running wild, when the **token** value is incorrect, as soon as refreshing the repositories starts.
* It keeps on running wild, even if restarted with a correct configuration file, until the device is rebooted!
* The original issue WRT an incorrect / outdated **cookie** value seems to be fixed (ai still have to check that a second time).

**Comment by Olf0** [comment]
* Rebooted, installed Storeman 0.0.33-3-Github (with a **broken cookie** configuration), no "Network error" (and no automatic rpo refresh): Yes, the original issue is fixed.
* Manually triggered refreshing that repos: "*An error occurred*" loop.

IMO refreshing the repos should work, even if authentication at OpenRepos fails.

P.S.: Thank you for cleaner up the configuration file, leaving only the necessary values in there.

**Comment by Olf0** [comment]
Tried to rectify the configuration values by manually logging into OpenRepos in Storeman 0.0.33-3-Github, rebooted: Even though it now shows "Logged in as olf" in the settings, the "An error occurred" notifications start, as soon as the repositories are refreshed.


I really wonder, why I did not run into this originally (with v0.0.33-3-OpenRepos and "Network error" due to an outdated / incorrect **cookie**, thus the authentication at OpenRepos should have failed, but no "*An error occurred*" notifications chain emitted), but now both v0.0.33-3 versions show this when authentication at OpenRepos fails, sometimes even after a reboot!?!

Still, v0.0.33-3-Github only seems to work as an upgrade path to resolve the original issue, if it is installed in a moment, when the cookie has not been outdated.
If not, a much more annoying issue arises (long chain of "*An error occurred*" notifications), which I have been unable to resolve at the GUI, yet.  Although the orientation issue is definitely fixed.

**Comment by Olf0** [comment]
BTW, I have had a bad gut feeling while testing tonight, by alternatingly installing two RPMs with exactly the same name, version and release number: I once learnt that one ***always*** increase at least the release number, as soon as a single character in the sources or the spec file is changed.
rpm, libzypp, pkcon etc. can / do not really distinguish between such two RPMs, despite their differing content.
Although I have no specific indication that the Storeman's files were not correctly installed each `pkcon install-local` run.

**Comment by Olf0** [comment]
A last observation with Storeman 0.0.33-3-Github, before reverting to tv0.0.33-3-OpenRepos and its original, working configuration file:

Exactly in the moment, when the chain of "*An error occurred*" starts (either automatically by Storeman' timeout or manually triggered by "Refresh cache"), two warnings are emitted at the command line:
`[W] unknown:461 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/PulleyMenuBase.qml:461:13: QML State: Binding loop detected for property "when"`
`[W] unknown:-1 - <Unknown File>: QML StateGroup: Can't apply a state change as part of a state definition.`

**Comment by Olf0** [comment]
... as these are the old points 5 and 6, maybe they **arr** related to this "follow up issue".

**Comment by Olf0** [comment]
And it was still there with Storeman 0.0.33-3-OpenRepos (as soon as the repos are refreshed).
I had to uninstall and reinstall Storeman to get rid of it!
Either the identical package numbers confuse `rpm` or something else may be strange with the packaging.

**Comment by mentaljam** [comment]
The "Failed to obtain authentication." error is a PackageKit error. It occurs when PackageKit fails to obtain required rights to perform system actions. In you case it occurs because you launched Storeman from the command line when normally it should be launched with the invoker (I've mentioned it [earlier](https://github.com/mentaljam/harbour-storeman/issues/82#issuecomment-460084425) in this thread).

**Comment by Olf0** [comment]
O.K. I missed or misunderstood this earlier.
Just an idea: Prefixing the error messages with their origin (i.e., in this case "[pkcon] ") would make them much easier to relate to their source).

Anyway, closing as the original issue seems to be solved.
