### ISSUE TITLE
install error repeatedly

### ISSUE THREAD

**Issue by objectifnul** [mentaljam/harbour-storeman#84]
Most Storeman installs fail with this error:

File './noarch/here-agreements-1.5.2-1.2.4.noarch.rpm' not found on medium 'https:
//store-repository.jolla.com/releases/3.0.1.11/jolla-hw/adaptation-qualcomm-sbj/armv7hl/?credentials=store

**Comment by mentaljam** [comment]
Please try to run `devel-su pkcon refresh`

**Comment by mentaljam** [comment]
Was the issue solved?

**Comment by objectifnul** [comment]
Yes, after "post_sfos-upgrade". Thx!
====
Le Dimanche 3 février 2019, Petr Tsymbarovich a écrit :
> Was the issue solved?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mentaljam/harbour-storeman/issues/84#issuecomment-46004157

-- 
CeD
