### ISSUE TITLE
Circle that showing icons for rating and making it favourite is not centered on this icons

### ISSUE THREAD

**Issue by atlochowski** [mentaljam/harbour-storeman#86]
Circle that showing icons for rating and making it favourite is not centered on this icon. This blinking circle is too much to left. It's happening on Jolla 1 and Jolla C, I don't have other devices  witch SFOS.

**Comment by mentaljam** [comment]
It seems to be not centered because the "Thumb Up" icon is not two-side-symmetric. I didn't come up with how to position the circle to make it looks centered on all resolutions so I just leaved it as it. I would appreciate someone who would suggest a solution.

**Comment by mentaljam** [comment]
On the other hand on all resolutions icons should keep its size is pxs. So may be I just need to add an offset...

**Comment by mentaljam** [comment]
After some investigation I realized there really was a problem with positioning of hints...
