### ISSUE TITLE
[Bug] Storeman 0.0.9 fails to handle plain text comments correctly 

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-storeman#9]
See <https://openrepos.net/comment/20113#comment-20113> for an example and the following comment: 
> IMO, Storeman should detect plain text messages (if the OpenRepos API offers that), and treat them accordingly.
> Alternatively (dirty workaround), you may convert plain text messages to HTML (as already the case with v0.0.9) *and* write them back as HTML messages (currently not the case).

**Comment by mentaljam** [comment]
Thank you for the report. Sorry I've not answered on your comment on OpenRepos.

**Comment by Olf0** [comment]
Absolutely O.K.; the issue belongs here, anyway. 
The comments on OpenRepos were just to demonstrate the issue and to explain the resulting garbage (not to leave these strange messages uncommented).  Then I did not find the time to file these issues here, until today.

**Comment by mentaljam** [comment]
Sorry, but I can't reproduce your issues or I misunderstood you. The OpenRepos has two types of text input: [Filtered HTML and Plain text](https://openrepos.net/filter/tips). Its API returns comments' text in the Filtered HTML format. When you edit a comment Silica TextArea considers it is a plain text so you see all the tags. After sending this text back to the OpenRepos it does some automatic recognition of paragraphs and line breaks.

So you can add any supported tag

    <strong>for example</strong>

And if you want to add a pseudo-tag you should use HTML codes

    &lt;for example&gt;

However I will force TextArea to use the plain text format. Another problem is that Silica Label does not know about Filtered HTML so not all tags are parsed. But it could be solved.

**Comment by mentaljam** [comment]
> Another problem is that Silica Label does not know about Filtered HTML so not all tags are parsed.

I was wrong. All tags are supported.

**Comment by Olf0** [comment]
> Sorry, but I can't reproduce your issues or I misunderstood you. 

From what I gathered until now, 50:50. ;)

> The OpenRepos has two types of text input: Filtered HTML and Plain text. 

When testing a bit yesterday ("Beerware comments"), I became aware, that one has to clearly differentiate between "input" by the user at GUI level, "submitting" / " retrieving" comments by Storeman via OpenRepos' web API, and "displaying comments" (either by Storeman or in a browser via OpenRepos' web-frontend) in both, thinking and communicating.

Thus my reply to your statement above is: 
- If you are addressing the OpenRepos' web API, and "input" is what Storeman submits to it: That seems likely, but I have not found any documentation for OpenRepos' web API (do you have a web link to it?). 
- The same two choices ("filtered HTML" and "plain text" formats) are offered as input formats in OpenRepos' web-frontend.  Additionally, when choosing "filtered HTML" format, one can either use a "rich text editor" (in which a comment is displayed as formatted text) or a "plain text editor" (in which a comment is displayed as raw HTML) to edit a comment. 
- OpenRepos internally "remembers" in which format a comment was created: When displaying or editing a comment, it interprets HTML tags and line breaks accordingly. 
- Storeman (as of v0.0.9 / v0.0.10) behaves as if choosing the "plain text editor" *and* "filtered HTML" format (in OpenRepos' web-frontend), when editing comments, regardless if they have been created in "plain text" or "filtered HTML" format.  This works well for "filtered HTML" formatted comments (except for a minor filtering strangeness, when inputting HTML tags, tested by pasting from the clipboard). 
- But that fails, when editing a comment (with Storeman), which was created in "plain text" format in OpenRepos' web-frontend.  It looks as if Storeman (or the way it retrieves comments from OpenRepos' web API) is converting "plain text" formatted comments to HTML (by inserting tags and quoting), and submits it as such to OpenRepos' web API.  But as OpenRepos still has this comment flagged as "plain text", raw HTML is displayed in OpenRepos web-frontend (instead of interpreted HTML).  This is the core point of this issue here. 

> Its API returns comments' text in the Filtered HTML format. 

Is this really the only format, in which comments (including those in "plain text" format) must be retrieved from OpenRepos' web API?

And if so, does OpenRepos' web API really not expose a flag or any other indication, that a comment is in "plain text" format (when created as such in OpenRepos' web-frontend)?

> When you edit a comment Silica TextArea considers it is a plain text so you see all the tags.

This is O.K. (and unrelated, as solely about "displaying" in Storeman, when creating or editing comments there), as it enables users to create and edit "filtered HTML" formatted comments as if using the "plain text editor" of OpenRepos' web-frontend. 

> After sending this text back to the OpenRepos it does some automatic recognition of paragraphs and line breaks.

Yet another (unrelated) topic.  Yes, I started to hate this buggy automatism years ago, using OpenRepos' web-frontend.  Unfortunately, I was unable to find a proper place to file a bug report (as OpenRepos does not seem to offer one, I would need to figure out, which software OpenRepos use for that, first; never have gotten around to that.)

**Comment by mentaljam** [comment]
Thank you for your... hmm... very detailed reply))

I've discussed this issue with @custodian and I think we've found a solution. As you correctly assumed OpenRepos stores a comment format. For now when Storeman send an edited comment it explicitly sets its format as Filtered HTML (as API returns this format). The only disadvantage of this solution is that Storeman reformats every edited comment to HTML.

> I was unable to find a proper place to file a bug report

But there is a menu entry "Feedback" on every page! And it works!

**Comment by Olf0** [comment]
Sorry if my explanations were too lengthy.

And tanks for contacting Basil.

Yes, always submitting comments explicitly as HTML (thus marking these comments as HTML formatted in OpenRepos internally) would solve this issue (if OpenRepos' web API allow for that) most easily.  
The inevitable fact, that plain text comments are then converted into HTML, is a minor loss, IMHO.
