### ISSUE TITLE
Trigger a pkcon refresh after an SFOS upgrade or manually

### ISSUE THREAD

**Issue by mentaljam** [mentaljam/harbour-storeman#90]
Submitter: Ritesh Patel
Feature request:
Please could you add an option to run pkcon refresh from a pulley menu (or even maybe run it when you first start the app after an upgrade)
It's an issue that trips everyone up at some point or other after an OS update so it's much needed.

**Comment by Olf0** [comment]
This issue title seems to be wrong, suggestion:
[Feature request] Trigger a pkcon refresh after a SFOS upgrade or manually
