### ISSUE TITLE
Can't  Comment  now

### ISSUE THREAD

**Issue by dashinfantry** [mentaljam/harbour-storeman#98]
.....

**Comment by mentaljam** [comment]
Please provide some additional info :)

**Comment by dashinfantry** [comment]
Xperia  XA2 Plus  with 3.0.10
--
傳送自 Android 版 myMail 星期三, 10 7月 2019, 06:01下午 +08:00 寄件人 Petr Tsymbarovich  notifications@github.com :

**Comment by Olf0** [comment]
@dashinfantry, what do you mean by stating "Can't Comment now"?
Please explain, as commenting is working well for long, except for issue #83.  Maybe this is a duplicate of that issue.

**Comment by dashinfantry** [comment]
I don't  know how it works now.Because I sold my Sailfish OS device and wait for cosmo communicator .
