### ISSUE TITLE
Issues with SailfishOS 3.1

### ISSUE THREAD

**Issue by mentaljam** [mentaljam/harbour-storeman#99]
- No installed packages
- No option to install a package
- Application shows as installed even when it's not

**Comment by atlochowski** [comment]
It's more than that. With SailfishOS 3.1 I can add repository but after that I can't install app. There is no install option in pulley, (even after refreshing cache from pulley). If I check description of app there is information that there is no available version.

**Comment by Neo2SHYAlien** [comment]
Same issue here. I already tried 
` pkcon refresh && pkcon update`
but without success. Storeman is a latest version 0.1.5

**Comment by Mariusmssj** [comment]
Yeah I am having the same issue, storeman can't be used properly with 3.1.0 update

**Comment by 127001** [comment]
As suggested in the comments on https://github.com/mentaljam/harbour-storeman/issues/100, I could solve the issue for my device with zypper refresh.
```

$ devel-su
$ pkcon refresh && pkcon install zypper
$ zypper refresh
```
After this, updates and new installs in Storeman started to work again.

**Comment by dashinfantry** [comment]
Can not install local RPM

**Comment by dashinfantry** [comment]
Cannot Comment apps

**Comment by atlochowski** [comment]
> As suggested in the comments on #100, I could solve the issue for my device with zypper refresh.
> 
> ```
> $ devel-su
> $ pkcon refresh && pkcon install zypper
> $ zypper refresh
> ```
> 
> After this, updates and new installs in Storeman started to work again.

Yes, I installed zypper and now storeman starts to work again :D

**Comment by ThijssjihT** [comment]
> As suggested in the comments on #100, I could solve the issue for my device with zypper refresh.
> 
> ```
> $ devel-su
> $ pkcon refresh && pkcon install zypper
> $ zypper refresh
> ```
> 
> After this, updates and new installs in Storeman started to work again.

Followed this, no errors, but also no fix.

**Comment by jkonecny12** [comment]
Also not working here.

**Comment by carmenfdezb** [comment]
Not working for me.
When I start storeman from Terminal and I try to add new repository, I get next error:

```
[nemo@Sailfish ~]$ harbour-storeman
[D] unknown:0 - Using Wayland-EGL
[W] unknown:0 - Categories dictionary does not contain tid 4206 - dictionary update can be required
[C] unknown:0 - Could not read "/var/cache/zypp/solv/openrepos-llelectronics/solv"
```
In storeman, it's showed next message: "An error ocurred. Failed to obtain authentication."
